name: Train Model to W&B (artifact)

on:
  # Correr automáticamente cuando termine el Preprocess
  workflow_run:
    workflows: ["Preprocess Raw Data to W&B (artifact)"]
    types: [completed]

  # También por cambios en el código o en este YAML
  push:
    branches: [ main ]
    paths:
      - 'train.py'
      - 'requirements.txt'
      - '.github/workflows/train_model.yml'

  # Y manualmente desde Actions
  workflow_dispatch:

jobs:
  train_model:
    # Si viene de workflow_run, solo corre si Preprocess terminó OK
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run train.py (consume processed y publica modelo)
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}   
          WANDB_PROJECT: MLOps-sklearn                  
        run: python src/model/train.py --IdExecution ${{ github.run_number }}
